version: 2

tools:
  satysfi-lint: &satysfi-lint
    # lint-command: "satysfi_lint"
    lint-command: "satysfi-typelint"

  lua-stylua: &lua-stylua
    format-command: "stylua -"
    format-stdin: true

languages:
  satysfi:
    - <<: *satysfi-lint
  lua:
    - <<: *lua-stylua
